#!/usr/bin/env bash
# This script displays all running processes in a user-oriented format with hierarchy and correct column headers

ps -eo user,lstart,cmd --forest | awk 'NR==1 {print "USER STARTED CMD"; next} {printf "%s %02d:%02d:%02d %s\n", $1, $(3), $(4), $(5), substr($0, index($0,$8))}'
